mysql:
  image: mysql:5.7
  environment:
    - MYSQL_ROOT_PASSWORD=dev
    - MYSQL_DATABASE=dev
    - MYSQL_USER=dev
    - MYSQL_PASSWORD=dev

nginx:
  image: phpdockerio/nginx:latest
  volumes:
      - ./app:/var/www/app
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  ports:
   - "8080:80"
  links:
   - fpm

fpm:
  build: .
  dockerfile: ./docker/php-fpm/5.6/Dockerfile
  volumes:
    - ./app:/var/www/app
    - ./docker/php-fpm/5.6/php-ini-overrides.ini:/etc/php5/fpm/conf.d/99-overrides.ini
  links:
    - mysql

