mysql:
  image: mysql:5.7
  env_file: .env

nginx:
  image: phpdockerio/nginx:latest
  volumes:
      - ./app:/var/www/app
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  ports:
   - "8080:80"
  links:
   - fpm

fpm:
  extends:
    file: docker-php.yml
    service: php70
  volumes:
    - ./app:/var/www/app
  links:
    - mysql

