nginx:
  build: ./services/nginx
  volumes:
    - ./app:/var/www
    - ./sites:/etc/nginx/conf.d
  ports:
   - "80:80"
   - "443:443"
  links:
   - php

php:
  build: ./services/php/7.0
  volumes:
    - ./app:/var/www
  links:
    - mysql

mysql:
  image: mysql
  ports:
    - "3306:3306"
  env_file: .env
  volumes:
    - ./var/storage/mysql:/var/lib/mysql

phpmyadmin:
  image: phpmyadmin/phpmyadmin
  ports:
   - "8080:80"
  environment:
    PMA_HOST: mysql
  links:
    - mysql

