version: '2'

#
# Services definition
#
services:
  nginx:
    build: ./services/nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./app:/var/www
      - ./sites:/etc/nginx/conf.d
    networks:
      - frontend
      - backend

  php:
    build: ./services/php/7.0
    volumes:
      - ./app:/var/www
    networks:
      - backend

  mysql:
    image: mysql
    env_file: .env
    volumes:
      - data-mysql:/var/lib/mysql
    networks:
      - backend

#
# Volumes definition
#
volumes:  
  data-mysql:
    driver: local

#
# Networks definition
#
networks:  
  frontend:
    driver: bridge
  backend:
    driver: bridge
